### ISSUE TITLE
Add robots.txt

### ISSUE THREAD

**Issue by lucasvo** [centrifuge/documentation#240]
We should add a robots.txt file to allow indexing

**Comment by lucasvo** [comment]
@sounak98 can this be closed?

**Comment by lucasvo** [comment]
The robots.txt file links to a sitemap that can't be found. please fix this: Sitemap: https://docs.centrifuge.io/sitemap/sitemap-index.xml

**Comment by lucasvo** [comment]
This also affects github.com/centrifuge/website

**Comment by sounak98** [comment]
https://github.com/centrifuge/documentation/pull/258
https://github.com/centrifuge/website/pull/286
