### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by ImdioR** [centrifuge/documentation#335]
![github3](https://user-images.githubusercontent.com/90972248/151671749-aa6caa66-bf14-41db-827a-537715925fca.png)

1) found broken links in DOC:
Read more about the bridge design in the ChainBridge Specification. The Centrifuge<>Ethereum bridge currently supports Substrate Native <> ERC20 token transfers.

[Link broken](https://github.com/ChainSafe/ChainBridge/blob/main/docs/spec.md)

2) Regarding the Operating Agreement of the SPVs.
This one: [broken](https://docs.google.com/document/d/14I8x16nRvSVgtnV6EoahZQ9GGVrdvKNbIK7tAN5gBaY/edit)

**Comment by devin-black** [comment]
This text is not part of docs anymore following changes since this issue was made, so closing
