### ISSUE TITLE
Shifted menu in mobile device

### ISSUE THREAD

**Issue by ImdioR** [centrifuge/documentation#409]
Hello
The left menu shifted outside and can not be accessible from a mobile device.

![image](https://user-images.githubusercontent.com/90972248/208265683-5e22ca1f-2c3c-4b4d-a48c-d7dbcb4460d7.png)
![image](https://user-images.githubusercontent.com/90972248/208265701-9a2e49fc-b439-4dc7-8af8-cf620a26406a.png)
![image](https://user-images.githubusercontent.com/90972248/208265755-4a06b023-c144-47a1-891c-4c198d16870f.png)

The resolution of the display doesn't matter. The issue with menu exist always.

**Comment by devin-black** [comment]
Fixed with new design!
