### ISSUE TITLE
Outdated screenshots in Set Up CFG Wallet

### ISSUE THREAD

**Issue by devin-black** [centrifuge/documentation#414]
Polkadot.js screenshots need to be updated for https://docs.centrifuge.io/use/setup-wallet/

**Comment by annamehr** [comment]
@devin-black was this part of yesterday's commit as well?

**Comment by devin-black** [comment]
@annamehr Nope haven't gotten to this, so this issue should stay open

**Comment by Rhanok09** [comment]
@devin-black we also need to look into scaling some of the screenshots in the governance documentation.

[Governance process](https://docs.centrifuge.io/use/governance-process/)
- Make the Cooling-off Period visual a little bigger (hard to read)

[Governance Proxy and Delegation](https://docs.centrifuge.io/use/governance-proxy-and-delegation/)
- Some of the screenshots need to be scaled down, they are too big.

The visuals in [Off-chain voting](https://docs.centrifuge.io/use/offchain-voting/) and [On-chain voting](https://docs.centrifuge.io/use/onchain-voting/) look ok, but take a look at them and adjust if you think.
